### ISSUE TITLE
unresolved import `actix_web::body::Body`

### ISSUE THREAD

**Issue by qxqxq** [pyrossh/rust-embed#174]
https://github.com/pyrossh/rust-embed/blob/master/examples/actix.rs

actix-web = "4.0.0"
actix-http = "3.0.4"

error[E0432]: unresolved import `actix_web::body::Body`
 --> src/controller/index.rs:6:5
  |
6 | use actix_web::body::Body;
  |     ^^^^^^^^^^^^^^^^^^^^^ no `Body` in `body`

Could you please provide an example of `actix-web = "4.0.0"`?

**Comment by AzureMarker** [comment]
@qxqxq See https://github.com/pyrossh/rust-embed/pull/175

**Comment by qxqxq** [comment]
> @qxqxq见#175

Thanks!
