### ISSUE TITLE
Having a fallback when an ENV variable does not exist for `interpolate-folder-path`

### ISSUE THREAD

**Issue by rbozan** [pyrossh/rust-embed#176]
Hi, thanks for the crate,

Basically I have the [interpolate-folder-path](https://github.com/pyros2097/rust-embed#interpolate-folder-path) functionality enabled and use this piece of code for loading in the assets:

```rust
#[derive(RustEmbed)]
#[folder = "$CURRENT_SCENARIO_DIR/output"]
pub struct Content;
```

However I would like to have an "empty" `Content` in this case when the ENV variable does not exist. You can of course circumvent this by somehow setting the ENV variable `CURRENT_SCENARIO_DIR` to some invalid path before starting the compilation, but is there not an easier way to fallback to something else?

The current behavior when the ENV variable does not exist is just failing to compile completely:
```sh
help: message: called `Result::unwrap()` on an `Err` value: LookupError { var_name: "CURRENT_SCENARIO_DIR", cause: NotPresent }
```

Another option (which would work for my use case) would be something like falling back to another ENV variable, so you could maybe do:
```rust
#[folder = "($CURRENT_SCENARIO_DIR || $PWD)/output"]
```

Thanks

**Comment by AzureMarker** [comment]
Have you tried setting the env variable in your build.rs script?

**Comment by AzureMarker** [comment]
Additionally, I would try to avoid having any logic in the folder string. That kind of thing should be in your build.rs script.

**Comment by rbozan** [comment]
Well I guess for my use case I can also use `[env]` in my Cargo config as that would fix it. But still it would be nice if an folder does not exist it wouldn't panic but you can silently ignore it so the `Content` in this case would just be empty as well. The issue can be closed though if you don't agree

**Comment by AzureMarker** [comment]
I recommend using the built-in functionality of https://doc.rust-lang.org/cargo/reference/build-scripts.html (or `[env]` as you suggested), especially if you need logic around the folder path.
