### ISSUE TITLE
sonatype-2021-4646

### ISSUE THREAD

**Issue by acim** [pyrossh/rust-embed#178]
cargo pants reports the following vulnerability:

Vulnerable Dependencies

[1/1] pkg:cargo/rust-embed-impl@6.2.0
1 known vulnerability found

Vulnerability Title: 1 vulnerability found
╭─────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ID          │ sonatype-2021-4646                                                                                                              │
├─────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Description │ 1 non-CVE vulnerability found. To see more details, please create a free account at https://ossindex.sonatype.org/ and request  │
│             │ for this information using your registered account                                                                              │
├─────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ CVSS Score  │ 7.8                                                                                                                             │
├─────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ CVSS Vector │ CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H                                                                                    │
├─────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Reference   │ https://ossindex.sonatype.org                                                                                                   │
╰─────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Inverse Dependency graph
rust-embed-impl 6.2.0 (git+https://github.com/pyrossh/rust-embed#451568cd0c93a9fd363829f54c17785e432bf4e8)
└── rust-embed 6.4.0 (git+https://github.com/pyrossh/rust-embed#451568cd0c93a9fd363829f54c17785e432bf4e8)
`
`

**Comment by pyrossh** [comment]
Hmm I don't know if that bug `../../../etc/passwd` applies here as well since we don't have a filesystem here. But I guess we could normalize the input . I'm guessing this vulnerability happens or is exposed during development as that is when we use the filesystem to serve the files.

Any ideas, should we normalize the input path in this case?
@AzureMarker

**Comment by acim** [comment]
Maybe check if canonical path starts with crate root?

**Comment by AzureMarker** [comment]
I thought we already patched this?

**Comment by pyrossh** [comment]
Yep just saw the code. It was implemented by you in this commit https://github.com/pyrossh/rust-embed/commit/e1720ce38452c7f94d2ff32d2c120d7d427e2ebe

**Comment by acim** [comment]
Can it just be that they have to recheck the project again? Maybe you should try to contact them as maintainers.

**Comment by AzureMarker** [comment]
@pyrossh I think the issue is that we didn't release the impl crate for the last two versions. It's still on 6.2.0:
![image](https://user-images.githubusercontent.com/4417660/172026950-ea4e154f-71b6-4c1b-80fe-b3b98325953f.png)

**Comment by pyrossh** [comment]
@AzureMarker the latest impl crate version is `v6.2.0`. The crate versions don't need to match. I tried it myself and got the same. I have added a `pants-ignore` file for this vulnerability. We actually fixed this issue and published it for `v6.2.0` of the impl crate.
https://github.com/pyrossh/rust-embed/commit/6aafae61081083794f5e72cc1e08830fd1a91382

**Comment by AzureMarker** [comment]
I think the confusion was that 6.2.0 of the main crate did have the bug, but it was fixed in the 6.2.0 version of the impl crate.
