### ISSUE TITLE
Avoid panicking if the folder is missing

### ISSUE THREAD

**Issue by SeriousBug** [pyrossh/rust-embed#180]
Small request for enhancement: would it be possible to avoid panicking if the embedded folder is missing?

```
error: proc-macro derive panicked
  --> src/static_files.rs:46:10
   |
46 | #[derive(RustEmbed)]
   |          ^^^^^^^^^
   |
   = help: message: #[derive(RustEmbed)] folder '/path/to/folder' does not exist. cwd: '/path/to/project'
```

Some people may find the panic useful, so maybe the macro could still panic for release builds, or only avoid panicking if a `allow_missing` flag is set.

My rationale for this is that I use RustEmbed to embed a javascript web app UI into the server. During CI tests, I build and test the server by itself without building the UI, so the folder is missing.

There are other ways to get around this like creating an empty folder before building the server, or keeping the empty folder in the repository. So this feature request isn't critical in any way, but may be useful.

**Comment by AzureMarker** [comment]
We can have better behavior here to generate a `compile_fail` statement, but we should still fail the build.

**Comment by SeriousBug** [comment]
expo's build tool completely deletes the folder before exporting, which ends up deleting the gitignore file and causes changes.

I ended up working around this by adding a build script that creates the folder if it is missing.

I see the value in failing the build, so I'll leave it up to you if you want to close this issue or not. Thanks for the suggestion!

**Comment by pyrossh** [comment]
@SeriousBug it would be weird to have a flag which behaves differently in debug vs release mode. Since you have already found a simple work around for this going to to close this.
