### ISSUE TITLE
What were the breaking changes between 5.9 and 6.4

### ISSUE THREAD

**Issue by andy5995** [pyrossh/rust-embed#181]
Do you have a doc somewhere that lists the breaking changes between major versions 5 and 6? I'm just looking for the quickest way to fix https://github.com/TelluricDeckay/telluricdeckay/blob/trunk/src/main.rs

```
error[E0277]: the trait bound `Translations: rust_embed::RustEmbed` is not satisfied
  --> src/main.rs:27:42
   |
27 |     i18n_embed::select(&language_loader, &translations, &requested_languages);
   |     ------------------                   ^^^^^^^^^^^^^ the trait `rust_embed::RustEmbed` is not implemented for `Translations`
   |     |
   |     required by a bound introduced by this call
```

**Comment by AzureMarker** [comment]
We have a changelog:
https://github.com/pyrossh/rust-embed/blob/master/changelog.md

Probably you need to update `i18n-embed` alongside `rust-embed`.

**Comment by andy5995** [comment]
Thanks @AzureMarker , all good now.
