### ISSUE TITLE
Single page application (SPA) example

### ISSUE THREAD

**Issue by frederikhors** [pyrossh/rust-embed#183]
I'm having a bit of difficulty using your example (with `axum` in this case) to host a single page application (SPA).

I have no trouble without `rust-embed` using a single line of code with `axum` ([from here](https://github.com/tokio-rs/axum/blob/main/examples/static-file-server/src/main.rs)):

```rust
app.fallback(get_service(ServeDir::new("./app/static")).handle_error(error_handler))
```

But I don't understand how to do with `rust-embed`.

The need is that every path typed by the user (and that is not an existent file such as `.js` or `.css` which obviously must be downloaded by the browser) leads to the "`index.html`" file in the root of my `static` dir.

If I use [your example code](https://github.com/pyrossh/rust-embed/blob/master/examples/axum.rs) I can see the route:

```rust
.route("/dist/*file", static_handler.into_service())
```

which has `/dist/*file` and I don't need that `/dist` becasue the `index.html` calls many files with custom paths, such as `/_works`, `menu`, `images`.

If I remove the `dist` part I get this error:

```
thread 'main' panicked at 'Invalid route: insertion failed due to conflict with previously registered route: /index.html'
```

Can you help me understand?

If I fix this I can create a PR for future people to come!

_I hope my problem is clear. Sorry if is not._

**Comment by AzureMarker** [comment]
You can call [`RustEmbed::get`] and if the result is `None` then fall back to returning the `index.html` file.

[`RustEmbed::get`]: https://docs.rs/rust-embed/6.4.0/rust_embed/trait.RustEmbed.html#tymethod.get

**Comment by frederikhors** [comment]
@AzureMarker thank you very much!

I'm starting with a small example here: https://github.com/frederikhors/rust-embed-spa.

I'm having trouble refactoring. I'll write in a few what I think is wrong.

**Comment by frederikhors** [comment]
I opened https://github.com/pyrossh/rust-embed/pull/184.
