### ISSUE TITLE
[Feature Request] Allow the folder attribute to be any const identifier

### ISSUE THREAD

**Issue by kyp44** [pyrossh/rust-embed#189]
It seems that the `folder` attribute for the `RustEmbed` derive macro can only be a string literal. I have a need to use this directory string elsewhere as well, so it would be great if I could specify the folder attribute using a `const` identifier (or even any `const` expression) so I can define it in a single place.

**Comment by AzureMarker** [comment]
The value needs to be used during the proc macro execution, which doesn't have access to the rest of your program. Proc macros receive the input as tokens, so we can't resolve the value of a variable, even if it's const.

**Comment by AzureMarker** [comment]
Thinking a little more on this, it _might_ work if `include_bytes` supports it, but I don't think it does.

**Comment by kyp44** [comment]
Yeah, I definitely see that now, I've written some proc macros myself and had not taken into account how they actually work. In particular, I imagine that a `const` value could be used in the debug case where the directory is searched at runtime since presumably the macro produces code in the host program that does this and thus would have access to a `const` identifier. However, in the release case I see that this would not be possible since the directory is read at _compile_ time instead.

I did a quick test and verified that you are correct in that neither `include_bytes` nor `include_str` work with `const` identifiers, and explicitly say that they require a string literal.

I tried another approach described in a reddit post I just made [here](https://www.reddit.com/r/learnrust/comments/xyyg7e/using_a_macro_inside_of_a_procedural_macro/), but it also didn’t work. I’ll also note that the `env` macro approach _does_ work for `include_bytes` and `include_str`. If you’re as stumped as I am, we’ll see if anyone in my reddit post has any ideas for workarounds.

**Comment by AzureMarker** [comment]
You can actually include whatever you want in attributes, it's just that right now the library expects a string. Whatever you write there will still just be unevaluated tokens to the macro though. The proc macro does read some metadata about the file (ex. hash, last modified time), so it does want the real path during its execution, but besides that it would technically be possible to accept an expression that resolves at compile time (ex. env macro) to a string that include_bytes would accept.

**Comment by kyp44** [comment]
Yeah, based on my experience, I assumed that the proc macro itself is specifically looking for a string literal. I'm guessing that the syntax tree for the attribute could just be the macro expression, which [does exist](https://docs.rs/syn/latest/syn/struct.ExprMacro.html) in `syn` for example. However, unless there's a a way inside the proc macro to actually evaluate the `env` macro I don't think it's possible to do this. It [sounds](https://stackoverflow.com/questions/49576878/how-do-i-evaluate-expressions-in-rusts-macro-system) like maybe this is just not possible.

Although, given that `include_bytes` does the same kind of things at compile time, it must be possible unless it's using some special black magic. I might look into how this is accomplished.

**Comment by AzureMarker** [comment]
If you use the `interpolate-folder-path` feature you can use environment variables in the folder string, but that doesn't help much since now you'd need to set an env variable in addition to the const.

**Comment by kyp44** [comment]
Yeah the `interpolate-folder-path` feature totally solved this for me. Maybe I should have completely read the docs before submitting and issue here!
