### ISSUE TITLE
Store the result from `mime_guess` statically at compile time?

### ISSUE THREAD

**Issue by BBaoVanC** [pyrossh/rust-embed#192]
The examples all show using `mime_guess` at runtime while serving the file to guess the mimetype, but it would be nice if there were a `mime_guess` feature that would make it statically compile the result of `mime_guess` into the `EmbeddedFile` type.

**Comment by pyrossh** [comment]
Yeah seems like a nice idea. Want to raise a PR for it?

**Comment by AzureMarker** [comment]
If implemented this should be behind a feature flag.

**Comment by BBaoVanC** [comment]
> Yeah seems like a nice idea. Want to raise a PR for it?

I'm not really sure how to implement it, but I could try if you could give some help

> If implemented this should be behind a feature flag.

Yeah, that's why I said it should be behind a feature called `mime_guess`
