### ISSUE TITLE
Getting error: pattern does not mention field `is_dir`

### ISSUE THREAD

**Issue by askonomm** [pyrossh/rust-embed#195]
As of half an hour ago, I'm getting this error in the 6.4.2 version of rust-embed. This is not happening on the newest version 6.5.0, but the 6.4.2 was also working yesterday and an existing version randomly breaking is pretty weird.

Full stacktrace:

```
error[E0027]: pattern does not mention field `is_dir`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-embed-impl-6.3.1/src/lib.rs:20:7
   |
20 |   for rust_embed_utils::FileEntry { rel_path, full_canonical_path } in rust_embed_utils::get_files(folder_path, &includes, &excludes) {
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing field `is_dir`
   |
help: include the missing field in the pattern
   |
20 |   for rust_embed_utils::FileEntry { rel_path, full_canonical_path, is_dir } in rust_embed_utils::get_files(folder_path, &includes, &excludes) {
   |                                                                  ~~~~~~~~~~
help: if you don't care about this missing field, you can explicitly ignore it
   |
20 |   for rust_embed_utils::FileEntry { rel_path, full_canonical_path, .. } in rust_embed_utils::get_files(folder_path, &includes, &excludes) {
   |                                                                  ~~~~~~

For more information about this error, try `rustc --explain E0027`.
error: could not compile `rust-embed-impl` due to previous error
```

**Comment by jaztec** [comment]
Is it possible this happened because the version was not updated in the fork but only after merge? Making the latest commit in the 6.4 minor version the one with changes?

**Comment by pyrossh** [comment]
Will be yanking 6.5.0, impl - 6.4.0 and utils 7.4.0 now so that we can address this issue https://github.com/pyrossh/rust-embed/issues/196 as well.
And reverting all changes to make it stable again.

**Comment by pyrossh** [comment]
@jaztec I updated all the versions and then published so that couldn't have happened. It seems like rust-embed-utils got updated to v7.4.0  by cargo and is conflicting with the other packages.  @askonomm what version was the rust-embed-utils crate if you remember. I don't think its possible to recreate it now though.

**Comment by askonomm** [comment]
> @jaztec I updated all the versions and then published so that couldn't have happened. It seems like rust-embed-utils got updated to v7.4.0 by cargo and is conflicting with the other packages. @askonomm what version was the rust-embed-utils crate if you remember. I don't think its possible to recreate it now though.

Unfortunately I don't remember, and can't check anymore as I've already updated to 6.5 which works just fine for me. Sorry about that, wish I could be of more help.

**Comment by pyrossh** [comment]
No probs thanks.

**Comment by AzureMarker** [comment]
@pyrossh The addition of the new public field in a public struct without a major version bump is probably the reason for this error.

**Comment by pyrossh** [comment]
@AzureMarker  Yep didn't think through it after the merge and ended up releasing a minor version instead.
