### ISSUE TITLE
cargo test fails

### ISSUE THREAD

**Issue by DusterTheFirst** [pyrossh/rust-embed#200]
Not all examples are defined in the `Cargo.toml`, such as `examples/salvo.rs`, so if `cargo test` is run without `--all-features` the tests will fail with a spam of `failed to resolve` errors as the salvo feature/other features are not enabled

**Comment by AzureMarker** [comment]
Should be fixed by #202

**Comment by pyrossh** [comment]
I've merged the changes thanks @DusterTheFirst
