### ISSUE TITLE
using with askama compile time templates

### ISSUE THREAD

**Issue by Sparkenstein** [pyrossh/rust-embed#210]
rust-embed worked really well for me, but earlier I was using `askama` templates for serving HTML. 
any examples on using rust embed with askama or any other compile time templates? 

Maybe we can also include it in official examples!

**Comment by pyrossh** [comment]
Hmm... if askama is already compiled, why would you need rust embed to serve html in that case? You would just use rust-embed to serve static assets on a static path in the router and use askama compiled templates to handle the rest of the routes.

**Comment by BBaoVanC** [comment]
> You would just use rust-embed to serve static assets on a static path in the router and use askama compiled templates to handle the rest of the routes.

This is what I'm doing by the way:

static routes: [`src/static_routes.rs`](https://github.com/BBaoVanC/bobashare/blob/bc1a846e03e21384c62ea7966808af1161d3a2cf/bobashare-web/src/static_routes.rs)
askama templates: [`src/views/`](https://github.com/BBaoVanC/bobashare/tree/bc1a846e03e21384c62ea7966808af1161d3a2cf/bobashare-web/src/views)
router: [`src/main.rs:172`](https://github.com/BBaoVanC/bobashare/blob/bc1a846e03e21384c62ea7966808af1161d3a2cf/bobashare-web/src/main.rs#L172-L173)

**Comment by Sparkenstein** [comment]
that's fair. I will try this and let you know. closing for now.
