### ISSUE TITLE
error[E0609]: no field `data` on type `Cow<'_, [u8]>`

### ISSUE THREAD

**Issue by ArunGust** [pyrossh/rust-embed#219]
Hey, I got below error, any idea about this issue

error[E0609]: no field `data` on type `Cow<'_, [u8]>`
  --> src\main.rs:23:25
   |
23 |           .body(content.data.into_owned()),

**Comment by pyrossh** [comment]
Have you tried any of the examples,
https://github.com/pyrossh/rust-embed/blob/master/examples/basic.rs
