### ISSUE TITLE
Rename RustEmbed trait to Embed?

### ISSUE THREAD

**Issue by timClicks** [pyrossh/rust-embed#222]
Would it be possible to shorten the name of the main trait exported by this library?

I don't see any particular reason to include the word "Rust" in the trait name, apart from it originating from a crate with the same name.

**Comment by pyrossh** [comment]
Nice Idea. But this has gotta be a collective decision? Can we get some upvotes.

**Comment by BBaoVanC** [comment]
Would be a breaking change and require major version bump, but I agree this makes sense to change.

**Comment by pyrossh** [comment]
Anyone want to submit a PR for this?

**Comment by osiewicz** [comment]
A non-breaking change would be to reexport `RustEmbed` as `Embed`, preserving RustEmbed in place (like so: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0037fc65e543296c1dc21af0235463c7)

**Comment by pyrossh** [comment]
Nice idea. We could update the docs and Readme as well for this so would be the new de-facto way.
