### ISSUE TITLE
`RustEmbed` derive macro is susceptible to naming collisions

### ISSUE THREAD

**Issue by hwittenborn** [pyrossh/rust-embed#229]
I noticed that the `RustEmbed` derive macro is susceptible to collisions in item names used in the macro. I encountered this issue earlier today from the use of [`Box`](https://github.com/pyrossh/rust-embed/blob/253340f329bea991dd83be345113b76ec2fc8c9d/impl/src/lib.rs#L176), which is being used as [GTK4's `Box`](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/struct.Box.html) in my crate.

I feel like the macro should be using absolute paths (`::std::boxed::Box` I think?) to avoid the issue.

**Comment by pyrossh** [comment]
Yep. You're right. Interested in a a PR?

**Comment by hwittenborn** [comment]
Sure thing @pyrossh! I'll go ahead and get one going.
