### ISSUE TITLE
Unable to read symbolic link in debug mode

### ISSUE THREAD

**Issue by Buckram123** [pyrossh/rust-embed#234]
RustEmbed::get fails to `get` a symbolic link file in debug mode, but suceeds in "release" see #235 for example

**Comment by pyrossh** [comment]
@Buckram123 Thanks for reporting this. Would you be interested in a PR for this fix? It seems to me we read the file directly here https://github.com/pyrossh/rust-embed/blob/master/utils/src/lib.rs#L136
What we need to do is read the file metadata and check if its a sym_link and if it is we need to use the `fs::read_link` fn to get the path to the actual file.

**Comment by pyrossh** [comment]
This fn seems to be a better option, `std::fs::canonicalize`

**Comment by Buckram123** [comment]
> @Buckram123 Thanks for reporting this. Would you be interested in a PR for this fix? It seems to me we read the file directly here https://github.com/pyrossh/rust-embed/blob/master/utils/src/lib.rs#L136 What we need to do is read the file metadata and check if its a sym_link and if it is we need to use the `fs::read_link` fn to get the path to the actual file.

Hey, thanks for a quick reply! Sure, would be cool to contribute here. I'll try to fix it on saturday :rocket:

**Comment by pyrossh** [comment]
Fixed in v8.3.0
