### ISSUE TITLE
Option to not include file contents

### ISSUE THREAD

**Issue by ddfisher** [pyrossh/rust-embed#238]
I'm working on an app which is compiled for both platform-native and WASM builds. We're currently bundling all the assets into the binary (using rust-embed) for both native and WASM, but we're in the process of moving many of the assets out of the binary for the WASM builds in order to enable faster loading times on web. We're planning on following the standard cache busting URL pattern by including the hash in the URL, so it'd be handy to be able to look up the hash by filename.  (It'd also be helpful to statically know the contents of the directory.)  Effectively, on WASM, we want exactly the metadata that rust-embed already provides, just without the actual contents of the files themselves.

I'm starting to look into implementing this. Is it something you'd be open to PRs for?

**Comment by pyrossh** [comment]
Yes we accept PRs. This would require a new feature.
